## 作業目標
1. 活用矩陣運算，實做線性代數
2. 作業重點
    * 線性代數公式應用
    * 矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

3. 題目: array1 = np.array([[10, 8], [3, 5]])
    * 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
    * 運用上列array計算特徵值、特徵向量?
    * 運用上列array計算SVD?

In [10]:
import numpy as np

In [11]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
print("原矩陣")
print(array1)
print("-----")

# 反矩陣
inv_array1 = np.linalg.inv(array1)
print("反矩陣")
print(inv_array1)
print("-----")

# 原矩陣 @ 反矩陣
print("原矩陣 @ 反矩陣")
print(array1 @ inv_array1)
print("-----")

print("原矩陣array1乘上其反矩陣inv_array1會得到一個二維的單位矩陣")

原矩陣
[[10  8]
 [ 3  5]]
-----
反矩陣
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
-----
原矩陣 @ 反矩陣
[[1. 0.]
 [0. 1.]]
-----
原矩陣array1乘上其反矩陣inv_array1會得到一個二維的單位矩陣


In [12]:
#2. 運用上列array計算特徵值、特徵向量?
values, vectors = np.linalg.eig(array1)

print("特徵值")
print(values)
print("-----")
print("特徵向量")
print(vectors)

特徵值
[13.  2.]
-----
特徵向量
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [13]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))